repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.29.0'
    hooks:
    -   id: yapf
        args: [--style=setup.cfg, -i]
