def validate_globals(global_var_names, cur_globals):
    """
    Validate that the list of provided global variable names exist in the global namespace
    and have defined values.

    Parameters
    ----------
    global_var_names : array
      Array of global variable names to test for existence.
    cur_globals : dict
      Current dictionary of global variables from where this function is called. Generated by calling `globals()`.

    Raises
    -------
    NameError
        If any global variable is undefined.
    """
    undefined_globals = []
    for var in global_var_names:
        if var not in cur_globals or not cur_globals[var]:
            print(f'Undefined global variable: {var}')
            undefined_globals.append(var)

    if undefined_globals:
        raise NameError(f'Undefined global variables: {undefined_globals}')
